TensorFlow gives you the flexibility and control with features like the Keras Functional API and Model Subclassing API for creation of complex topologies

In [4]:
import tensorflow as tf

In [5]:
print("tensorflow version",tf.__version__)

tensorflow version 2.12.0


In [6]:
#load data set:data set of MNIST DATA SET
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test = x_train/255.0 , x_test/255.0

build tf.keras.sequential model

In [8]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),#convert to 2D to 1D
    tf.keras.layers.Dense(128,activation='relu'),#performs linear operstion and  relu function use to introduce linearity
    tf.keras.layers.Dropout(0.2),#use to  prevent overfitting in neural network models
    tf.keras.layers.Dense(10)
]) # tensor flow is composed of layers here Flatten,DEnse and dropout are layers

In [9]:
predictions=model(x_train[:1]).numpy() #return the vectors of logits and log outs scores
predictions#.numpy() is use to convert output of tensor flow to numpy array

array([[-0.6153436 ,  0.00541205, -0.1261281 , -0.13369784,  0.32420993,
        -0.68975544,  0.22558253, -0.78242266,  0.4240322 , -0.49366078]],
      dtype=float32)

tf.nn.softmax function use to convert this logits to probabilities

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.05981317, 0.11127243, 0.09755744, 0.09682174, 0.15305226,
        0.05552393, 0.13867763, 0.05060988, 0.16911884, 0.06755274]],
      dtype=float32)

In TensorFlow, a vector is a one-dimensional array-like data structure that contains elements of the same data type. 

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

2.8909411

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
#it sets up the optimizer, loss function, and evaluation metric(s) to be used during the training process. 

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2978 - accuracy: 0.9135
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1410 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1059 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0872 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0760 - accuracy: 0.9763


In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0768 - accuracy: 0.9751 - 688ms/epoch - 2ms/step


[0.07684449106454849, 0.9750999808311462]

In [18]:
# return the model to probability 
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [19]:
probability_model(x_test[:5])# evaluate for first five data set

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.5408488e-07, 1.1359396e-08, 7.7320583e-05, 3.7399121e-04,
        1.6709765e-12, 5.7179918e-08, 5.7417070e-12, 9.9954611e-01,
        1.6981231e-06, 4.4856495e-07],
       [1.1733506e-07, 1.7071143e-02, 9.8291910e-01, 7.7157229e-06,
        5.0104882e-14, 1.3254248e-06, 3.8120828e-07, 7.6211149e-11,
        2.3790112e-07, 1.0547075e-11],
       [7.0392974e-07, 9.9944180e-01, 1.7152213e-05, 1.3947642e-05,
        2.3891991e-05, 1.5617699e-05, 9.7876800e-06, 3.2315953e-04,
        1.5267581e-04, 1.2227035e-06],
       [9.9924833e-01, 9.4223559e-08, 1.5777786e-04, 2.9866512e-06,
        3.2225026e-07, 5.4055795e-06, 4.6838468e-05, 1.7037269e-06,
        8.5858193e-07, 5.3554145e-04],
       [1.0642759e-06, 1.4067069e-09, 3.3508272e-06, 8.2990215e-07,
        9.9599010e-01, 7.6356673e-07, 2.6747268e-06, 2.9668585e-05,
        2.9099678e-07, 3.9712959e-03]], dtype=float32)>

logits refer to the raw, unnormalized output of a model before applying any activation function. Logits are usually obtained from the final layer of the model, representing the scores or values associated with each class in a classification problem.